# Generated by Django 3.1.1 on 2020-10-31 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionistdisplaymessage',
            name='message',
        ),
        migrations.AddField(
            model_name='receptionistdisplaymessage',
            name='meeting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='people.meeting'),
        ),
        migrations.AlterField(
            model_name='receptionistdisplaymessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 16, 58, 20, 306949), null=True),
        ),
    ]
