# Generated by Django 3.1.1 on 2020-10-31 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201031_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receptionistdisplaymessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 17, 4, 1, 671424), null=True),
        ),
    ]
