# Generated by Django 3.1.1 on 2020-11-22 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201031_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receptionistdisplaymessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 0, 18, 42, 481452), null=True),
        ),
    ]
