# Generated by Django 3.1.1 on 2020-11-22 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20201122_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionistdisplaymessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 3, 35, 48, 147818), null=True),
        ),
    ]
