# Generated by Django 3.1.1 on 2020-11-22 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20201122_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, default='a@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='receptionistdisplaymessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 3, 37, 39, 778563), null=True),
        ),
    ]
